"""initializing tables

Revision ID: 029678825ced
Revises: 
Create Date: 2025-03-23 01:57:56.024683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029678825ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('office_location', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_year', sa.String(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_semesters_professor_id_professors')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('class_room', sa.String(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_classes_semester_id_semesters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_status', sa.Boolean(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_registrations_class_id_classes')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_registrations_student_id_students')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('classes')
    op.drop_table('semesters')
    op.drop_table('students')
    op.drop_table('professors')
    # ### end Alembic commands ###
